# Generated by Django 5.2.11 on 2026-02-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('GASTRONOMIA', 'Gastronomia'), ('FARMACIA', 'Farmácia'), ('MERCADO', 'Mercado'), ('SERVICOS', 'Serviços'), ('OUTROS', 'Outros')], max_length=20)),
                ('subcategoria', models.CharField(blank=True, help_text='Ex: Pizza, Hambúrguer', max_length=50)),
                ('foto_url', models.URLField(blank=True, help_text='Link da imagem da logo ou capa', max_length=500)),
                ('bairro', models.CharField(default='Centro', max_length=50)),
                ('telefone', models.CharField(help_text='Apenas números, ex: 21999999999', max_length=20)),
                ('destaque', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
