# Generated by Django 5.2.11 on 2026-02-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioOnibus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(default='Guapimirim', max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('numero_linha', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('MUNICIPAL', 'Municipal (Circular)'), ('INTERMUNICIPAL', 'Intermunicipal'), ('VAN', 'Transporte Alternativo (Van)')], default='INTERMUNICIPAL', max_length=20)),
                ('tarifa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('horarios', models.TextField(help_text='Separe os horários por vírgula ou descreva a frequência')),
                ('via', models.CharField(blank=True, help_text='Ex: Via Parada Modelo', max_length=50)),
                ('observacoes', models.TextField(blank=True, help_text='Ex: Não roda aos domingos')),
            ],
        ),
    ]
