# Generated by Django 5.2.11 on 2026-02-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_horarioonibus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastronomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('RESTAURANTE', 'Restaurante'), ('LANCHONETE', 'Lanchonete'), ('PIZZARIA', 'Pizzaria'), ('CAFE', 'Café / Doceria'), ('CERVEJARIA', 'Cervejaria / Bar')], max_length=20)),
                ('especialidade', models.CharField(help_text='Ex: Comida Caseira, Massas, Hambúrguer Artesanal', max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='gastronomia/')),
                ('bairro', models.CharField(default='Centro', max_length=50)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('delivery', models.BooleanField(default=True)),
                ('vegano_vegetariano', models.BooleanField(default=False, verbose_name='Opções Veg/Veggie')),
                ('destaque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('POUSADA', 'Pousada'), ('HOTEL', 'Hotel'), ('CHALE', 'Chalé'), ('CAMPING', 'Camping')], default='POUSADA', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='hospedagem/')),
                ('bairro', models.CharField(help_text='Ex: Barreira, Caneca Fina, Centro', max_length=50)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('site_reserva', models.URLField(blank=True, help_text='Link para Booking ou site próprio')),
                ('cafe_da_manha', models.BooleanField(default=True)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('piscina', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='comercio',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='comercio',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comercio',
            name='foto',
            field=models.ImageField(blank=True, help_text='Upload da logo ou foto da fachada', null=True, upload_to='comercio/'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='categoria',
            field=models.CharField(choices=[('FARMACIA', 'Farmácia'), ('MERCADO', 'Mercado'), ('SERVICOS', 'Serviços'), ('PETSHOP', 'Pet Shop'), ('OUTROS', 'Outros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='subcategoria',
            field=models.CharField(blank=True, help_text='Ex: Oficina, Estética, Papelaria', max_length=50),
        ),
        migrations.AlterField(
            model_name='horarioonibus',
            name='destino',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='horarioonibus',
            name='horarios',
            field=models.TextField(help_text='Separe os horários por vírgula'),
        ),
        migrations.AlterField(
            model_name='horarioonibus',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='horarioonibus',
            name='origem',
            field=models.CharField(default='Guapimirim', max_length=100),
        ),
        migrations.AlterField(
            model_name='horarioonibus',
            name='tipo',
            field=models.CharField(choices=[('MUNICIPAL', 'Municipal (Circular)'), ('INTERMUNICIPAL', 'Intermunicipal'), ('VAN', 'Transporte Alternativo (Van)'), ('TREM', 'Trem (Ferrovia)')], default='INTERMUNICIPAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='horarioonibus',
            name='via',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
