# Generated by Django 5.2.11 on 2026-02-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gastronomia_hospedagem_remove_comercio_foto_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('foto', models.ImageField(upload_to='turismo/')),
                ('bairro', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('introducao', models.TextField(max_length=200)),
                ('descricao_completa', models.TextField()),
                ('como_chegar', models.TextField()),
                ('destaque', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ponto Turístico',
                'verbose_name_plural': 'Pontos Turísticos',
            },
        ),
        migrations.AlterField(
            model_name='gastronomia',
            name='categoria',
            field=models.CharField(choices=[('RESTAURANTE', 'Restaurante'), ('LANCHONETE', 'Lanchonete'), ('PIZZARIA', 'Pizzaria'), ('CAFE E PADARIA', 'Café / Padaria'), ('CERVEJARIA', 'Cervejaria / Bar'), ('SORVETERIA', 'Sorveteria / Doceria'), ('OUTROS', 'Outros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gastronomia',
            name='especialidade',
            field=models.CharField(help_text='Ex: Comida Caseira, Massas, Hambúrguer Artesanal', max_length=200),
        ),
        migrations.AlterField(
            model_name='hospedagem',
            name='telefone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
