# Generated by Django 5.2.11 on 2026-02-19 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_turismo_alter_gastronomia_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turismo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='turismo/'),
        ),
        migrations.CreateModel(
            name='TurismoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='turismo/galeria/')),
                ('turismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='api.turismo')),
            ],
        ),
    ]
