# Generated by Django 5.2.11 on 2026-02-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_turismo_foto_turismofoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastronomia',
            name='horario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
