# Generated by Django 5.2.11 on 2026-03-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gastronomia_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercio',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='comercio',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='comercio',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='turismofoto',
            name='bairro',
            field=models.CharField(default='Centro', max_length=50),
        ),
        migrations.AddField(
            model_name='turismofoto',
            name='categoria',
            field=models.CharField(choices=[('CACHOEIRAS', 'Cachoeiras'), ('TRILHAS', 'Trilhas'), ('HISTORIA', 'História'), ('PARQUES', 'Parques')], default='CACHOEIRAS', max_length=20),
        ),
        migrations.AddField(
            model_name='turismofoto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='turismofoto',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turismofoto',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='turismofoto',
            name='foto',
            field=models.ImageField(blank=True, help_text='Upload da logo ou foto da fachada', null=True, upload_to='comercio/'),
        ),
        migrations.AddField(
            model_name='turismofoto',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='turismofoto',
            name='nome',
            field=models.CharField(default='Sem Nome', max_length=100),
        ),
        migrations.AddField(
            model_name='turismofoto',
            name='subcategoria',
            field=models.CharField(blank=True, help_text='Ex: Oficina, Estética, Papelaria', max_length=50),
        ),
        migrations.AddField(
            model_name='turismofoto',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='bairro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='categoria',
            field=models.CharField(choices=[('MERCADO', 'Mercado'), ('FARMACIA', 'Farmácia'), ('PETSHOP', 'Pet-Shop'), ('VESTUARIO', 'Vestuário'), ('ELETRONICOS', 'Eletrônicos'), ('SERVICOS', 'Serviços'), ('VARIEDADES', 'Variedades')], default='VARIEDADES', max_length=50),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='comercio/'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='turismo',
            name='nome',
            field=models.CharField(default='Nome Aqui', max_length=200),
        ),
    ]
