# Generated by Django 5.2.11 on 2026-03-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_comercio_criado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroGratuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Gastronomia', 'Gastronomia'), ('Hospedagem', 'Hospedagem'), ('Comércio', 'Comércio em Geral')], max_length=50)),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True)),
                ('faz_entrega', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('opcoes_veganas', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cadastros_pendentes/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('analisado', models.BooleanField(default=False, help_text='Marque aqui quando já tiver visto este cadastro')),
            ],
            options={
                'verbose_name': 'Cadastro Gratuito Pendente',
                'verbose_name_plural': 'Cadastros Gratuitos Pendentes',
            },
        ),
    ]
