# Generated by Django 5.2.11 on 2026-03-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cadastrogratuito'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrogratuito',
            name='descricao',
            field=models.TextField(blank=True, help_text='Texto descritivo para a página exclusiva', null=True),
        ),
        migrations.AddField(
            model_name='cadastrogratuito',
            name='horario_funcionamento',
            field=models.CharField(blank=True, help_text='Ex: Seg a Dom, das 18h às 23h', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cadastrogratuito',
            name='instagram',
            field=models.CharField(blank=True, help_text='Ex: @seunegocio', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cadastrogratuito',
            name='link_cardapio',
            field=models.URLField(blank=True, help_text='Link para cardápio digital ou site', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cadastrogratuito',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número do WhatsApp', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comercio',
            name='foto_galeria_1',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/comercio/'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='foto_galeria_2',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/comercio/'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='foto_galeria_3',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/comercio/'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='horario_funcionamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comercio',
            name='link_cardapio',
            field=models.URLField(blank=True, help_text='Catálogo ou Site', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comercio',
            name='slug',
            field=models.SlugField(blank=True, help_text='Deixe em branco para preencher automaticamente', max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gastronomia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gastronomia',
            name='foto_galeria_1',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/gastronomia/'),
        ),
        migrations.AddField(
            model_name='gastronomia',
            name='foto_galeria_2',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/gastronomia/'),
        ),
        migrations.AddField(
            model_name='gastronomia',
            name='foto_galeria_3',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/gastronomia/'),
        ),
        migrations.AddField(
            model_name='gastronomia',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gastronomia',
            name='link_cardapio',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gastronomia',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='foto_galeria_1',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/hospedagem/'),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='foto_galeria_2',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/hospedagem/'),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='foto_galeria_3',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/hospedagem/'),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='horario_funcionamento',
            field=models.CharField(blank=True, help_text='Horários de Check-in e Check-out', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
