# Generated by Django 5.2.11 on 2026-05-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cadastrogratuito_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrogratuito',
            name='email',
            field=models.EmailField(blank=True, help_text='Email para contato', max_length=255, null=True),
        ),
    ]
