# Generated by Django 5.2.11 on 2026-05-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cadastrogratuito_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastrogratuito',
            options={'verbose_name': 'Cadastro/Anúncio Pendente', 'verbose_name_plural': 'Cadastros e Anúncios Pendentes'},
        ),
        migrations.AddField(
            model_name='cadastrogratuito',
            name='foto_galeria_1',
            field=models.ImageField(blank=True, null=True, upload_to='cadastros_pendentes/galeria/'),
        ),
        migrations.AddField(
            model_name='cadastrogratuito',
            name='foto_galeria_2',
            field=models.ImageField(blank=True, null=True, upload_to='cadastros_pendentes/galeria/'),
        ),
        migrations.AddField(
            model_name='cadastrogratuito',
            name='foto_galeria_3',
            field=models.ImageField(blank=True, null=True, upload_to='cadastros_pendentes/galeria/'),
        ),
        migrations.AddField(
            model_name='cadastrogratuito',
            name='order_id',
            field=models.CharField(blank=True, help_text='ID único para a InfinitePay', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cadastrogratuito',
            name='plano',
            field=models.CharField(choices=[('GRATUITO', 'Gratuito'), ('OURO', 'Ouro')], default='GRATUITO', max_length=20),
        ),
        migrations.AddField(
            model_name='cadastrogratuito',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20),
        ),
    ]
