# Generated by Django 5.2.11 on 2026-05-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_cadastrogratuito_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('GASTRONOMIA', 'Gastronomia'), ('AVENTURA', 'Aventura'), ('CULTURA', 'Cultura'), ('ESPORTE', 'Esporte'), ('MUSICA', 'Música'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50)),
                ('descricao_curta', models.TextField(help_text='Resumo que aparece no card da página inicial', max_length=250)),
                ('data_hora', models.CharField(help_text='Ex: Sábado, 08:00', max_length=100)),
                ('local', models.CharField(help_text='Ex: Praça Central', max_length=150)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para ocultar o evento da página principal')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento Local',
                'verbose_name_plural': 'Eventos Locais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
