# Generated by Django 5.2.11 on 2026-06-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrogratuito',
            name='email',
            field=models.EmailField(default='', help_text='Email para contato', max_length=255),
        ),
    ]
